#########################
#####   AngelChest  #####
#########################

# After this amount of seconds, the AngelChest is automatically destroyed
# and drops its contents
# Default is 600 seconds = 10 minutes
angelchest-duration: 600

# When the block where the player dies is not empty (e.g. water, lava, half slab)
# we will search for an empty block inside max-radius. Default is 10 blocks.
# If there is absolutely no free space inside this radius, the chest
# is spawned exactly where the player died and may replace a transparent block, so
# do not set this value too low.
max-radius: 10

# When set to true, players will receive a message telling them where the AngelChest
# is located.
show-location: false

# Should we check for updates?
# When enabled, a message is printed in the console if a new version has
# been found, and OPs will be notified when they join the server.
# When set to true, we will check for updates on startup and every 24 hours
# When set to on-startup, we will only check on startup
# When set to false, don't check for updates
check-for-updates: true

#########################
#### disabled worlds ####
#########################

# You can disable AngelChest for certain worlds. Each world's name has to
# be on a separate line, starting with a hyphen and followed by a space

# Example:
#
# disabled-worlds:
# - world_nether
# - world_the_end

disabled-worlds:

#########################
##### localization ######
#########################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green     
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

##### Hologram text and name of the AngelChest. %s is the player's name. \n is a new line.
hologram-text: "&a&l[AngelChest]&r\n&b%s"
angelchest-inventory-name: "&a[AngelChest] &b%s&r"

##### English
message-all-your-angelchests-were-already-unlocked: "&eAll your AngelChests were already unlocked."
message-angelchest-created: "&aAn Angel collected your stuff and put it into a chest located at the place of your death."
message-angelchest-disappeared: "&cYou were too slow... Your AngelChest has disappeared and dropped its contents."
message-error-players-only: "&cError: This command can only be run by players."
message-inventory-was-empty: "&eAn Angel searched for your stuff but could not find anything."
message-not-allowed-to-break-other-angelchests: "&cYou are not allowed to break other people's AngelChest."
message-not-allowed-to-open-other-angelchests: "&cYou are not allowed to open other people's AngelChest."
message-unlocked-more-angelchests: "&aYou have unlocked %d AngelChests."
message-unlocked-one-angelchest: "&aYou have unlocked your AngelChest."
message-you-dont-have-any-angelchests: "&eYou don't have any AngelChests."
message-you-got-part-of-your-inventory-back: "&eYou got a part of your inventory back, but some items are still in the AngelChest."
message-you-got-your-inventory-back: "&aYou got your inventory back!"
message-angelchest-location: "&eLocation of your AngelChest: %s"

##### Chinese Simplified 简体中文 - Thanks to qsefthuopq for translating! -> https://www.spigotmc.org/members/qsefthuopq.339953/
#message-all-your-angelchests-were-already-unlocked: "&e你所有的天御之箱都已解锁."
#message-angelchest-created: "&a一位善良的天使捡起了你的物品并放到了你死亡地点附近的箱子内."
#message-angelchest-disappeared: "&c你来晚了... 你的天御之箱消失且物品掉到了地上."
#message-error-players-only: "&c错误: 这个指令只能由玩家执行."
#message-inventory-was-empty: "&e天使并没有找到你掉落的物品."
#message-not-allowed-to-break-other-angelchests: "&c你不能破坏其它玩家的天御之箱."
#message-not-allowed-to-open-other-angelchests: "&你不能打开其它玩家的天御之箱."
#message-unlocked-more-angelchests: "&a你解锁了%d 的天御之箱."
#message-unlocked-one-angelchest: "&你解锁了你的的天御之箱."
#message-you-dont-have-any-angelchests: "&e你没有任何的天御之箱."
#message-you-got-part-of-your-inventory-back: "&e你取回了一些物品,但还有一些物品在天御之箱内."
#message-you-got-your-inventory-back: "&a你成功地取回了你的物品!"
#message-angelchest-location: "&eLocation of your AngelChest: %s"

##### Chinese Traditional 繁體中文 - Thanks to maoding for translating! -> https://www.spigotmc.org/members/maoding.400505/
#message-all-your-angelchests-were-already-unlocked: "&e所有的小天使箱子已被解鎖"
#message-angelchest-created: "&a一個善良的小天使幫你把所有的掉落物蒐集起來了，並放置在您死亡的地點"
#message-angelchest-disappeared: "&c你晚了一步... 小天使箱子已經消失，你的物品也掉了出來"
#message-error-players-only: "&c錯誤： 該指令只能由玩家使用"
#message-inventory-was-empty: "&e小天使發現你在死亡時未掉落任何物品"
#message-not-allowed-to-break-other-angelchests: "&c你無法破壞其他人的小天使箱子!"
#message-not-allowed-to-open-other-angelchests: "&c你無法使用其他人的小天使箱子!"
#message-unlocked-more-angelchests: "&a成功解鎖 %d個 小天使箱子"
#message-unlocked-one-angelchest: "&a成功將你的小天使箱子解鎖了"
#message-you-dont-have-any-angelchests: "&e你沒有任何小天使箱子"
#message-you-got-part-of-your-inventory-back: "&e你取回了一部分的物品，但仍有物品遺留在小天使箱子裡"
#message-you-got-your-inventory-back: "&a成功將物品取回!"
#message-angelchest-location: "&eLocation of your AngelChest: %s"

##### French - Thanks to AngelCynara for translating! -> https://www.spigotmc.org/members/angelcynara.398643/ 
#message-all-your-angelchests-were-already-unlocked: "&eTout vos AngeCoffres sont débloqués."
#message-angelchest-created: "&aUn Ange a recupérer votre stuff et l'as mis dans un coffre à l'endroit de votre mort."
#message-angelchest-disappeared: "&cVous avez été trop lent , votre stuff a disparu."
#message-error-players-only: "&c Erreur : Cette commande ne peut être effectué que par des joueurs."
#message-inventory-was-empty: "&e L'Ange n'as rien trouver dans votre inventaire au moment de votre mort."
#message-not-allowed-to-break-other-angelchests: "&c L'Ange vous interdit de casser l' AngeCoffre d'un autre joueur."
#message-not-allowed-to-open-other-angelchests: "&cL'Ange vous interdit d'ouvrir l' AngeCoffre d'un autre joueur."
#message-unlocked-more-angelchests: "&aVous avez débloqué %d AngeCoffres."
#message-unlocked-one-angelchest: "&aVous avez debloqué votre AngeCoffre."
#message-you-dont-have-any-angelchests: "&eVous n'avez pas de AngeCoffre."
#message-you-got-part-of-your-inventory-back: "&eVous avez récuperer une partie de votre inventaire , mais il en reste dans l' AngeCoffre."
#message-you-got-your-inventory-back: "&aVous avez récuperer votre inventaire."
#message-angelchest-location: "&eLocation of your AngelChest: %s"

##### German
#message-all-your-angelchests-were-already-unlocked: "&eAlle deine AngelChests waren bereits aufgeschlossen."
#message-angelchest-created: "&aEin Angel hat deine Sachen eingesammelt und sie in einer Kiste am Ort deines Todes gelagert."
#message-angelchest-disappeared: "&cDu warst zu langsam... deine AngelChest ist verschwunden hat ihren Inhalt fallen gelassen."
#message-error-players-only: "&cFehler: Dieser Befehl kann nur von Spielern benutzt werden."
#message-inventory-was-empty: "&eEin Engel hat nach deinen Sachen gesucht aber konnte nichts finden."
#message-not-allowed-to-break-other-angelchests: "&cDu darfst die AngelChest von anderen Spielern nicht zerstören."
#message-not-allowed-to-open-other-angelchests: "&cDu darfst die AngelChest von anderen Spielern nicht öffnen."
#message-unlocked-more-angelchests: "&aDu hast %d AngelChests aufgeschlossen."
#message-unlocked-one-angelchest: "&aDu hast deine AngelChest aufgeschlossen."
#message-you-dont-have-any-angelchests: "&eDu hast keine AngelChest."
#message-you-got-part-of-your-inventory-back: "&eEin Teil deines Inventars wurde wiederhergestellt, aber manche Sachen sind noch in der AngelChest."
#message-you-got-your-inventory-back: "&aDein Inventar wurde wiederhergestellt!"
#message-angelchest-location: "&ePosition deiner AngelChest: %s"

##### Polish – Polski
#message-all-your-angelchests-were-already-unlocked: "&eWszystkie twoje AnielskieSkrzynie zostaly juz odblokowane."
#message-angelchest-created: "&aAniol zebral twoje rzeczy i wlozyl je do skrzyni znajdujacej sie w miejscu twojej smierci."
#message-angelchest-disappeared: "&cByles zbyt wolny... Twoja AnielskaSkrzynia pekla i upuscila zawartosc."
#message-error-players-only: "&cError: Ta komenda moze byc wywolana wylacznie przez graczy."
#message-inventory-was-empty: "&eAniol szukal twoich rzeczy, ale nic nie mogl znalezc."
#message-not-allowed-to-break-other-angelchests: "&cNie mozesz niszczyc AnielskichSkrzyn innych graczy."
#message-not-allowed-to-open-other-angelchests: "&cNie mozesz otwierac AnielskichSkrzyn innych graczy."
#message-unlocked-more-angelchests: "&aOdblokowales %d Anielskie(ich)Skrzyn(ie)."
#message-unlocked-one-angelchest: "&aOdblokowales AnielskaSkrzynie."
#message-you-dont-have-any-angelchests: "&eNie masz zadnej AnielskiejSkrzyni"
#message-you-got-part-of-your-inventory-back: "&eOdzyskales czesc ekwipunku, ale niektore przedmioty wciaz znajduja sie w AnielskiejSkrzyni."
#message-you-got-your-inventory-back: "&aOdzyskales swoj ekwipunek!"
#message-angelchest-location: "&eLokalizacja Twojej AnielskiejSkrzyni: %s"

#########################
#####     Done!     #####
#########################

# please do not change the following line manually!
config-version: 9
